openapi: 3.0.0
info:
  title: Construction.Account.Admin Account Management Versions API
  version: '1.0'
  contact:
    name: Autodesk Plaform Services
    url: https://aps.autodesk.com/
    email: aps.help@autodesk.com
  termsOfService: https://www.autodesk.com/company/legal-notices-trademarks/terms-of-service-autodesk360-web-services/forge-platform-web-services-api-terms-of-service
  x-support: https://stackoverflow.com/questions/tagged/autodesk-platform-services
  description: 'The Account Admin API automates creating and managing projects, assigning and managing project users, and managing member and partner company directories. You can also synchronize data with external systems.

    '
servers:
- url: https://developer.api.autodesk.com
security:
- 2-legged: []
- 3-legged: []
tags:
- name: Versions
paths:
  /data/v1/projects/{project_id}/versions/{version_id}:
    get:
      tags:
      - Versions
      operationId: getVersion
      summary: Get a Version
      description: 'Returns the specified version of an item.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    patch:
      tags:
      - Versions
      operationId: patchVersion
      summary: Update a Version
      description: 'Updates the properties of the specified version of an  item. Currently, you can only change the name of the version.


        **Note:** This operation is not supported for BIM 360 and ACC. If you want to rename a version, create a new version with a new name.

        '
      security:
      - 2-legged:
        - data:write
      - 3-legged:
        - data:write
  /data/v1/projects/{project_id}/versions/{version_id}/item:
    get:
      tags:
      - Versions
      operationId: getVersionItem
      summary: Get Item by Version
      description: 'Returns the item corresponding to the specified version.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/versions/{version_id}/refs:
    get:
      tags:
      - Versions
      operationId: getVersionRefs
      summary: List Related Resources for a Version
      description: "Returns the resources (items, folders, and versions) that have a custom relationship with the specified version.\n\nCustom relationships can be established between a version of an item and other resources within the data domain service (folders, items, and versions).\n\n- Each relationship is defined by the id of the object at the other end of the relationship, together with type, attributes, and relationships links.\n- Callers will typically use a filter parameter to restric[...]"
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/versions/{version_id}/relationships/refs:
    get:
      tags:
      - Versions
      operationId: getVersionRelationshipsRefs
      summary: List Custom Relationships for a Version
      description: "Returns the custom relationships for the specified version. \n\nCustom relationships can be established between a version of an item and other resources within the data domain service (folders, items, and versions).\n\n- Each relationship is defined by the id of the object at the other end of the relationship, together with type, specific reference meta including extension data.\n- Callers will typically use a filter parameter to restrict the response to the custom relationsh[...]"
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    post:
      tags:
      - Versions
      operationId: createVersionRelationshipsRef
      summary: Create a Custom Relationship for a Version
      description: Creates a custom relationship between a version of an item and another resource within the data domain service (folder, item, or version).
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
  /projects/{project_id}/versions/{version_id}/relationships/links:
    get:
      tags:
      - Versions
      operationId: getVersionRelationshipsLinks
      summary: List Links for a Version
      description: 'Returns a collection of links for the specified version of an item. Custom relationships can be established between a version of an item and other external resources residing outside the data domain service. A link’s href defines the target URI to access the resource.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/versions:
    post:
      tags:
      - Versions
      operationId: createVersion
      summary: Create a Version
      description: 'Creates a new versions of an existing item.


        Before creating a new version you must create a storage location for the version in OSS, and upload the file to that location. For more details about the workflow, see the tutorial on uploading a file.


        This operation also allows you to create a new version of an item by copying a specific version of an existing item from another folder within the project. The new version becomes the tip version of the item.


        Use the [Create an Item](/en/docs/data/v2/reference/http/projects-project_id-items-POST/) operation to copy a specific version of an existing item as a new item in another folder.


        This operation can also be used to delete files on BIM360 Document Management. For more information, please refer to the delete and restore a file tutorial.


        Before you use the Data Management API to access BIM 360 Docs files, you must provision your app through the BIM 360 Account Administrator portal. For details, see the [Manage Access to Docs tutorial](/en/docs/bim360/v1/tutorials/getting-started/manage-access-to-docs/).


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
  /data/v1/projects/{project_id}/versions/{version_id}/downloadFormats:
    get:
      tags:
      - Versions
      operationId: getVersionDownloadFormats
      summary: List Supported Download Formats
      description: 'Returns a list of file formats the specified version of an item can be downloaded as.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/versions/{version_id}/downloads:
    get:
      tags:
      - Versions
      operationId: getVersionDownloads
      description: 'Returns the list of file formats of the specified version of an item currently available for download.


        **Note:** This operation is not fully implemented as yet. It currently returns an empty data object.'
      summary: List Available Download Formats
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
components:
  securitySchemes:
    2-legged:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged-implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
x-stoplight:
  id: zm6m3b30rcbon
