openapi: 3.0.0
info:
  title: Construction.Account.Admin Account Management Items API
  version: '1.0'
  contact:
    name: Autodesk Plaform Services
    url: https://aps.autodesk.com/
    email: aps.help@autodesk.com
  termsOfService: https://www.autodesk.com/company/legal-notices-trademarks/terms-of-service-autodesk360-web-services/forge-platform-web-services-api-terms-of-service
  x-support: https://stackoverflow.com/questions/tagged/autodesk-platform-services
  description: 'The Account Admin API automates creating and managing projects, assigning and managing project users, and managing member and partner company directories. You can also synchronize data with external systems.

    '
servers:
- url: https://developer.api.autodesk.com
security:
- 2-legged: []
- 3-legged: []
tags:
- name: Items
paths:
  /data/v1/projects/{project_id}/items/{item_id}:
    get:
      tags:
      - Items
      operationId: getItem
      summary: Get an Item
      description: 'Retrieves an item. Items represent Word documents, Fusion 360 design files, drawings, spreadsheets, etc.


        The tip version for the item is included in the included array of the payload.

        To retrieve multiple items, see the ListItems command.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    patch:
      tags:
      - Items
      operationId: patchItem
      summary: Update an Item
      description: 'Updates the ``displayName`` of the specified item. Note that updating the ``displayName`` of an item is not supported for BIM 360 Docs or ACC items.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:write
      - 3-legged:
        - data:write
  /data/v1/projects/{project_id}/items/{item_id}/parent:
    get:
      tags:
      - Items
      operationId: getItemParentFolder
      summary: Get Parent of an Item
      description: 'Returns the parent folder of the specified item.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/items/{item_id}/relationships/refs:
    get:
      tags:
      - Items
      operationId: getItemRelationshipsRefs
      summary: List Custom Relationships for an Item
      description: 'Returns the custom relationships that are associated with the specified item. Custom relationships can be established between an item and other resources within the ``data`` domain service (folders, items, and versions).


        Each relationship is defined by the ID of the object at the other end of the relationship, together with type, specific reference meta including extension data.

        Callers will typically use a filter parameter to restrict the response to the custom relationship types (``filter[meta.refType]``) they are interested in.

        The response body will have an included array that contains the resources in the relationship, which is essentially what is returned by the [List Related Resources for an Item](/en/docs/data/v2/reference/http/projects-project_id-items-item_id-refs-GET/) operation.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    post:
      tags:
      - Items
      operationId: createItemRelationshipsRef
      summary: Create a Custom Relationship for an Item
      description: Creates a custom relationship between an item and another resource within the data domain service (folder, item, or version).
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
  /data/v1/projects/{project_id}/items/{item_id}/refs:
    get:
      tags:
      - Items
      operationId: getItemRefs
      summary: List Related Resources for an Item
      description: 'Returns the resources (items, folders, and versions) that have a custom relationship with the specified item. Custom relationships can be established between an item and other resources within the data domain service (folders, items, and versions).



        Each relationship is defined by the ID of the object at the other end of the relationship, together with type, attributes, and relationships links.

        Callers will typically use a filter parameter to restrict the response to the custom relationship types (``filter[meta.refType]``) they are interested in.



        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/items/{item_id}/relationships/links:
    get:
      tags:
      - Items
      operationId: getItemRelationshipsLinks
      summary: List Relationship Links for an Item
      description: "Returns a list of links for the specified item. \n\nCustom relationships can be established between an item and other external resources residing outside the data domain service. A link’s ``href`` attribute defines the target URI to access a resource.\n\n**Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). "
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/items/{item_id}/tip:
    get:
      tags:
      - Items
      operationId: getItemTip
      summary: Get Tip Version of an Item
      description: 'Returns the latest version of the specified item. A project can contain multiple versions of a resource item. The latest version is referred to as the tip version, which is returned by this operation.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/items/{item_id}/versions:
    get:
      tags:
      - Items
      operationId: getItemVersions
      summary: List all Versions of an Item
      description: 'Lists all versions of the specified item. A project can contain multiple versions of a resource item.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/items:
    post:
      tags:
      - Items
      operationId: createItem
      summary: Create an Item
      description: "Creates the first version of a file (item). To create additional versions of an item, use POST versions.\n\nBefore you create the first version of an item, you must create a placeholder for the file, and upload the file to the placeholder. For more details about the workflow, see the tutorial on uploading a file.\n\nThis operation also allows you to create a new item by copying a specific version of an existing item to another folder. The copied version becomes the first vers[...]"
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
components:
  securitySchemes:
    2-legged:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged-implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
x-stoplight:
  id: zm6m3b30rcbon
