openapi: 3.0.0
info:
  title: Construction.Account.Admin Account Management Folders API
  version: '1.0'
  contact:
    name: Autodesk Plaform Services
    url: https://aps.autodesk.com/
    email: aps.help@autodesk.com
  termsOfService: https://www.autodesk.com/company/legal-notices-trademarks/terms-of-service-autodesk360-web-services/forge-platform-web-services-api-terms-of-service
  x-support: https://stackoverflow.com/questions/tagged/autodesk-platform-services
  description: 'The Account Admin API automates creating and managing projects, assigning and managing project users, and managing member and partner company directories. You can also synchronize data with external systems.

    '
servers:
- url: https://developer.api.autodesk.com
security:
- 2-legged: []
- 3-legged: []
tags:
- name: Folders
paths:
  /data/v1/projects/{project_id}/folders/{folder_id}:
    get:
      tags:
      - Folders
      operationId: getFolder
      summary: Get a Folder
      description: 'Returns the folder specified by the ``folder_id`` parameter from within the project identified by the ``project_id`` parameter. All folders and subfolders within a project (including the root folder) have a unique ID.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    patch:
      tags:
      - Folders
      operationId: patchFolder
      summary: Modify a Folder
      description: 'Renames, moves, hides, or unhides a folder. Marking a BIM 360 Docs folder as hidden effectively deletes it. You can restore it by changing its ``hidden`` attribute. You can also move BIM 360 Docs folders by changing their parent folder.


        You cannot permanently delete BIM 360 Docs folders. They are tagged as hidden folders and are removed from the BIM 360 Docs UI and from regular Data Management API responses. You can use the hidden filter (``filter[hidden]=true``) to get a list of deleted folders with the [List Folder Contents](/en/docs/data/v2/reference/http/projects-project_id-folders-folder_id-contents-GET/) operation.


        Before you use the Data Management API to access BIM 360 Docs folders, provision your app through the BIM 360 Account Administrator portal. For details, see the [Manage Access to Docs tutorial](/en/docs/bim360/v1/tutorials/getting-started/manage-access-to-docs/).


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](/en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:write
      - 3-legged:
        - data:write
      x-folder-id: projects-project_id-folders-folder_id-PATCH
  /data/v1/projects/{project_id}/folders/{folder_id}/parent:
    get:
      tags:
      - Folders
      operationId: getFolderParent
      summary: Get Parent of a Folder
      description: 'Returns the parent folder of the specified folder. In a project, folders are organized in a hierarchy. Each folder except for the root folder has a parent folder.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
      x-folder-id: projects-project_id-folders-folder_id-parent-GET
  /data/v1/projects/{project_id}/folders/{folder_id}/contents:
    get:
      tags:
      - Folders
      operationId: getFolderContents
      summary: List Folder Contents
      description: 'Returns a list of items and folders within the specified folder. Items represent word documents, fusion design files, drawings, spreadsheets, etc.


        The resources contained in the ``included`` array of the response are their tip versions.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/folders/{folder_id}/refs:
    get:
      tags:
      - Folders
      operationId: getFolderRefs
      summary: List Related Resources for a Folder
      description: 'Returns the resources (items, folders, and versions) that have a custom relationship with the specified folder. Custom relationships can be established between a folder and other resources within the data domain service (folders, items, and versions).


        Each relationship is defined by the id of the object at the other end of the relationship, together with type, attributes, and relationships links.

        Callers will typically use a filter parameter to restrict the response to the custom relationship types (``filter[meta.refType]``) they are interested in.


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/folders/{folder_id}/search:
    get:
      tags:
      - Folders
      operationId: getFolderSearch
      summary: List Folder and Subfolder Contents
      description: "Searches the specified folder and its subfolders and returns a list of the latest versions of the items you can access.\n\n\nUse the ``filter`` query string parameter to narrow down the list as appropriate. You can filter by the following properties of the version payload: \n\n- ``type`` property, \n- ``id`` property, \n- any of the attributes object properties. \n\nFor example, you can filter by ``createTime`` and ``mimeType``. It returns tip versions (latest versions) of pr[...]"
      security:
      - 3-legged:
        - data:read
        - data:search
  /data/v1/projects/{project_id}/folders/{folder_id}/relationships/refs:
    get:
      tags:
      - Folders
      operationId: getFolderRelationshipsRefs
      summary: List Custom Relationships for a Folder
      description: "Returns the custom relationships associated with the specified folder. Custom relationships can be established between a folder and other resources within the data domain service (folders, items, and versions).\n\nEach relationship is defined by the ID of the object at the other end of the relationship, together with type, specific reference meta including extension data.\nCallers will typically use a filter parameter to restrict the response to the custom relationship types [...]"
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
    post:
      tags:
      - Folders
      operationId: createFolderRelationshipsRef
      summary: Create a Custom Relationship for a Folder
      description: Creates a custom relationship between a folder and another resource within the data domain service (folder, item, or version).
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
  /data/v1/projects/{project_id}/folders/{folder_id}/relationships/links:
    get:
      tags:
      - Folders
      operationId: getFolderRelationshipsLinks
      summary: List Relationship Links for a Folder
      description: "Returns a list of links for the specified folder. \n\nCustom relationships can be established between a folder and other external resources residing outside the data domain service. A link’s ``href`` attribute defines the target URI to access a resource.\n\n**Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). "
      security:
      - 2-legged:
        - data:read
      - 3-legged:
        - data:read
  /data/v1/projects/{project_id}/folders:
    post:
      tags:
      - Folders
      operationId: createFolder
      summary: Create a Folder
      description: 'Creates a new folder in the specified project. Use the ``parent`` attribute in the request body to specify where in the hierarchy the new folder should be located. Folders can be nested up to 25 levels deep.


        Use the `Modify a Folder </en/docs/data/v2/reference/http/projects-project_id-folders-folder_id-PATCH/>`_ operation to delete and restore folders.


        Before you use the Data Management API to access BIM 360 Docs folders, provision your app through the BIM 360 Account Administrator portal. For details, see the [Manage Access to Docs tutorial](/en/docs/bim360/v1/tutorials/getting-started/manage-access-to-docs/).


        **Note:** This operation supports Autodesk Construction Cloud (ACC) Projects. For more information, see the [ACC Platform API documentation](https://en.docs.acc.v1/overview/introduction/). '
      security:
      - 2-legged:
        - data:create
      - 3-legged:
        - data:create
components:
  securitySchemes:
    2-legged:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged-implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
    3-legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
x-stoplight:
  id: zm6m3b30rcbon
